// Copyright (c) 2016 Onegini. All rights reserved.

#import <Foundation/Foundation.h>

@class ONGClient, OGConfigModel;

NS_ASSUME_NONNULL_BEGIN

/**
 * `ONGClientBuilder` is responsible for setting up SDK.
 *
 * SDK setup:
 *
 * In order to instantiate SDK you have to set at least `configModel` and `X509PEMCertificates`.
 * If one or both are not set, `ONGClientBuilder` will try to retrieve missing values from `OneginiConfigModel` class
 * generated by SDK configurator tool. If it is impossible to locate `OneginiConfigModel` - SDK can not be configured
 * correctly and exception is raised.
 */
@interface ONGClientBuilder : NSObject

/**
 * Set instance of `OGConfigModel` used for SDK configuration. This value can not be `nil`.
 *
 * @param configModel Instance of `OGConfigModel` used for SDK configuration.
 */
- (instancetype)setConfigModel:(OGConfigModel *)configModel;

/**
 * Flag instructing SDK to store cookies between requests. `YES` by default.
 *
 * @param storeCookies Whether or not to store cookies between requests.
 */
- (instancetype)setStoreCookies:(BOOL)storeCookies;

/**
 *  If App wants to use an embedded UIWebView instead of the external Safari browser for users registration
 *  then this parameter must be set to `YES`. `NO` by default.
 *
 *  @param useEmbeddedWebView Whether or not to use embedded web view for users registration.
 *
 */
- (instancetype)setUseEmbeddedWebView:(BOOL)useEmbeddedWebView;

/**
 *  For verification of the bundled DER encoded CA X509 certificates,
 *  the App must provide a list of matching PEM base64 encoded certificates for each bundled DER encoded CA X509 certificate to this client.
 *  The PEM base64 encoded certificates must be stripped from their armor (remove ---BEGIN CERTIFICATE--- & ---END CERTIFICATE---)
 *
 *  This method must be called before any service request is made, preferably after initialization.
 *  If certificate verification fails prior to making a service request, an Exception is thrown.
 *
 *  To convert a DER encoded certificate to PEM, use the following openssl command:
 *  openssl x509 -in <filename>.cer -inform der -out <filename>.pem -outform pem
 *  Do not include the PEM files themselved in App bundle!
 *
 *  @param certificates Array of PEM base64 encoded certificates without armor
 */
- (instancetype)setX509PEMCertificates:(NSArray<NSString *> *)certificates;

/**
 * Set up SDK and return configured instance of `ONGClient` using builder's values.
 * Subsequent calls will not take any effect on the instantiated `ONGClient`.
 *
 * @return configured instance of `ONGClient`
 *
 * @warning In case `ONGClientBuilder` doesn't have required values (`configModel` and `X509PEMCertificates`) and can not
 * retrieve them from `OneginiConfigModel` class (generated by SDK Configurator) - `ONGSDKInitializationException` will be thrown.
 */
- (ONGClient *)build;

@end

NS_ASSUME_NONNULL_END